### ISSUE TITLE
Compatibilité tuya conservée ?

### ISSUE THREAD

**Issue by clemorphy** [n3odym3/LSC_Smart-Connect_Indoor_Camera_Hack#4]
Bonjour,

Après root et application du patch sur la caméra LSC pour récupération du flux RTSP, conserve-t-on quand-même la compatibilité avec les applis tuya / smartlife ?

Merci

**Comment by adjivas** [comment]
Salut,

Oui, après l'application de ce patch, tu peux toujours utiliser l'application tuya.

Si toute fois ce n'est pas ton but, je te recommande la lecture de ceci :
[Can I use the device OFFLINE (disconnected from tuya servers) ?](https://github.com/guino/BazzDoorbell/wiki/Can-I-use-the-device-OFFLINE-(disconnected-from-tuya-servers)-%3F)

**Comment by clemorphy** [comment]
Merci @adjivas pour ta réponse rapide et précise.
Dans l'immédiat je souhaite conserver l'app, mais une fois que le flux RSTP sera configuré sur mon home assistant, c'est intéressant de savoir qu'on peut couper facilement les communications avec les serveurs tuya (option 1 de ton lien) ou un peu moins facilement avec tout internet (option 2 de ton lien).
